# 곱셈

(세 자리 수) × (세 자리 수)는 다음과 같은 과정을 통하여 이루어진다.


(1)과 (2)위치에 들어갈 세 자리 자연수가 주어질 때 (3), (4), (5), (6)위치에 들어갈 값을 구하는 프로그램을 작성하시오.

In [17]:
a= int(input())
b_lst = list(map(int, str(input())))
b = 0

for i in range(3):
  print((a * b_lst[2-i]))

for j in range(3):
  b += b_lst[2-j] * (10**j)

print(a*b)

472
385
2360
3776
1416
181720